[package]
name = "brace-parser"
version = "0.1.0"
authors = ["Daniel Balcomb <daniel.balcomb@gmail.com>"]
description = "A lightweight parser combinator library."
license = "MIT OR Apache-2.0"
edition = "2018"
